# Generated by Django 5.1 on 2024-08-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='phone',
        ),
    ]
